version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
      - image: circleci/postgres
        environment:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: test_pass
    environment:
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
         name: yarn install
         command: yarn install --check-files
      - run:
         name: db create
         command: bundle exec rake db:create
      - run:
         name: db migrate
         command: bundle exec rake db:migrate
