version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node
      - image: circleci/postgres
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
         name: yarn install --check-files
